FROM python:3

WORKDIR C:\Users\Nevetha\AML\Assignment_4

COPY app.py .
COPY score.py .
COPY test_1.py .
COPY finalized_mode.sav .
COPY vector_model.sav .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "./app.py"]